SYSTEM:
  gpus: [0,1]
  cudnn:
    benchmark: false
    deterministic: true
    enable: true

DATASET:
  name: 'Avenue'
  seed: 2020
  read_format: 'opencv'
  channel_num: 3
  channel_name: 'rgb'
  train:
    data_path: './data/Avenue/training/frames'
    clip_length: 5
    sampled_clip_length: 5
    frame_step: 1
    clip_step: 1
    gt_path: './data/Avenue'
  val:
    data_path: './data/Avenue/testing/frames'
    clip_length: 5
    sampled_clip_length: 5
    frame_step: 1
    clip_step: 1
    gt_path: './data/Avenue'
  number_of_class: 1
  score_normalize: false
  score_type: 'normal'
  decidable_idx: 4
  decidable_idx_back: 0
  smooth:
    guassian: true
    guassian_sigma: [3,5,15,10,20,30]
  mini_dataset:
    samples: 100
  evaluate_function:
    name: 'ScoreAUCMetrics'
    result_type: 'score'

ARGUMENT:
  train:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
    fliplr:
      use: false
      p: 0.5
    flipud:
      use: false
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      height: 256
      width: 256
      position: 'center'
  val:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

MODEL:
  name: 'anopcn'
  type: 'ame2e'
  parts: ['meta_G', 'AnoPcn', 'meta_D', 'PixelDiscriminator', 'auxiliary_F', 'FlowNet2']
  hooks:
    train: ['AnoPCNEvaluateHook', 'VisScoreHook']
    val: ['AnoPCNEvaluateHook']
  discriminator_channels: [128,256,512,512]
  auxiliary:
    optical_flow:
      name: 'flownet2'
      model_path: './pretrained_model/FlowNet2_checkpoint.pth.tar'
  
TRAIN:
  engine_name: 'ANOPCNTrainer'
  batch_size: 4
  start_step: 0
  max_steps: 160944
  dynamic_steps: [0, 2000, 3832]
  log_step: 100
  vis_step: 3832
  mini_eval_step: 3000
  eval_step: 3832
  save_step: 3832
  epochs: 1
  losses: ['loss_GANLoss_cuda', 0.25, 'GANLoss', [['gan_mode', 'lsgan'], ['target_real_label', 1.0], ['target_fake_label', 0.0]], 'loss_GradientLoss_cuda', 1.0, 'GradientLoss', [], 
           'loss_IntentsityLoss_cuda', 1.0, 'IntensityLoss', [], 'loss_OpticalflowSqrtLoss_cuda', 2.0, 'L2Loss', []]
  mode: 'adversarial'
  adversarial:
    optimizer:
      include: ['G', 'D']
      name: 'adam'
      lrs: [0.0002, 0.00002]
      weight_decay: 0.0
    scheduler:
      use: false
      name: 'WarmupCosLR'
      step_size: 1000
      steps: [10000, 15000]
      gamma: 0.1
      T_max: 3832
      eta_min: 0
      warmup_factor: 0.001
      warmup_iters: 7664
      warmup_method: 'linear'

VAL:
  engine_name: 'ANOPCNInference'
