SYSTEM:
  multigpus: false
  num_gpus: 2
  gpus: [0,1]
  cudnn:
    benchmark: false
    deterministic: true
    enable: true
  distributed:
    use: false
LOG:
  log_output_dir: './output/log'
  tb_output_dir: './output/tensorboard'
  vis_dir: './output/vis'
  
DATASET:
  name: 'shanghai'
  seed: 2020
  read_format: 'opencv'
  channel_num: 3
  channel_name: 'rgb'
  train:
    data_path: './data/shanghai/training/frames'
    clip_length: 32
    sampled_clip_length: 32
    frame_step: 1
    clip_step: 1
    execute_test: false
    gt_path: './data/shanghai/testing/test_frame_mask'
  val:
    data_path: './data/shanghai/testing/frames'
    clip_length: 2
    sampled_clip_length: 2
    frame_step: 1
    clip_step: 1
    gt_path: './data/shanghai/testing/test_frame_mask'
  number_of_class: 1
  score_normalize: true
  score_type: 'abnormal'
  decidable_idx: 1
  decidable_idx_back: 1
  smooth:
    guassian: true
    guassian_sigma: [3,5,15,10,20,30]
  mini_dataset:
    samples: 100
  evaluate_function:
    name: 'ScoreAUCMetrics'
    result_type: 'score'
AUGMENT:
  train:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
    fliplr:
      use: true
      p: 0.5
    flipud:
      use: false
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      hight: 256
      width: 256
      position: 'center'
  val:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
MODEL:
  name: 'stae'
  type: 'e2e'
  parts: ['meta_STAE', 'STAutoEncoderCov3D']
  hooks:
    train: ['stae.STAEEvaluateHook', 'base.VisScoreHook']
    val: ['stae.STAEEvaluateHook']

TRAIN:
  engine_name: 'STAETrainer'
  batch_size: 32
  start_step: 0
  max_steps: 20000
  log_step: 5
  vis_step: 1000
  mini_eval_step: 500
  eval_step: 2000
  save_step: 5000
  epochs: 1
  losses: ['loss_RecLoss_cuda', 1.0, 'L2Loss', [], 'loss_WeightedPredLoss_cuda', 1.0, WeightedPredLoss, []]
  mode: 'general'
  general:
    optimizer:
      include: ['STAE']
      name: 'adam'
      lrs: [1e-3]
      momentum: 0.9
      weight_decay: 0.0001
      nesterov: false
    scheduler:
      use: true
      name: 'WarmupCosLR'
      step_size: 1000
      steps: [10000, 15000]
      gamma: 0.1
      T_max: 3000
      eta_min: 0
      warmup_factor: 0.001
      warmup_iters: 1000
      warmup_method: 'linear'
  split: ''
  model_output: './output/models'
  checkpoint_output: './output/checkpoint'
  pusedo_data_path: ''
VAL:
  engine_name: 'STAEInference'
  name: ''
  path: ''
  batch_size: 2
  result_output: './output/results'

