SYSTEM:
  gpus: [0,1]
  cudnn:
    benchmark: true
    deterministic: false
    enable: true
  
DATASET:
  name: 'Shanghai'
  seed: 2020
  read_format: 'opencv'
  train:
    data_path: './data/shanghai/training/frames'
    clip_length: 2
    sampled_clip_length: 2
    clip_step: 1
    gt_path: './data/shanghai/testing/test_frame_mask'
  val:
    data_path: './data/shanghai/testing/frames'
    clip_length: 2
    sampled_clip_length: 2
    clip_step: 1
    gt_path: './data/shanghai/testing/test_frame_mask'
  number_of_class: 1
  score_normalize: true
  score_type: 'abnormal'
  decidable_idx: 1
  decidable_idx_back: 0
  smooth:
    guassian: true
    guassian_sigma: [3,5,15,10,20,30]
  mini_dataset:
    samples: 100
  evaluate_function:
    name: 'ScoreAUCMetrics'
    result_type: 'score'

AUGMENT:
  train:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
    fliplr:
      use: true
      p: 0.5
    flipud:
      use: false
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      hight: 256
      width: 256
      position: 'center'
  val:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
    fliplr:
      use: true
      p: 0.5
    flipud:
      use: false
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      hight: 256
      width: 256
      position: 'center'
MODEL:
  name: 'anopred'
  type: 'ame2e'
  parts: ['meta_G', 'AnoPredGeneratorUnet', 'meta_D', 'PixelDiscriminator', 'auxiliary_F', 'LiteFlowNet']
  hooks:
    train: ['AnoPredEvaluateHook', 'VisScoreHook']
    val: ['AnoPredEvaluateHook']
  discriminator_channels: [128,256,512,512]
  auxiliary:
    optical_flow:
      name: 'liteflownet'
      model_path: './pretrained_model/liteflownet/network-sintel.pytorch'

TRAIN:
  batch_size: 4
  start_step: 0
  max_steps: 20000
  log_step: 5
  vis_step: 1000
  mini_eval_step: 500
  eval_step: 2000
  save_step: 5000
  losses: ['loss_GANLoss_cuda', 0.25, 'GANLoss', [['gan_mode', 'lsgan'], ['target_real_label', 1.0], ['target_fake_label', 0.0]], 'loss_GradientLoss_cuda', 1.0, 'GradientLoss', [], 
           'loss_IntentsityLoss_cuda', 1.0, 'IntensityLoss', [], 'loss_OpticalflowLoss_cuda', 2.0, 'L1Loss', []]
  mode: 'adversarial'
  adversarial:
    optimizer:
      include: ['G', 'D']
      name: 'adam'
      lrs: [0.0002, 0.00002]
      weight_decay: 0.0001
    scheduler:
      use: true
      name: 'WarmupCosLR' # 'stepLR'| 'cosLR' | 'WarmupCosLR' | 'WarmupMultiStepLR'
      step_size: 1000
      steps: [10000, 15000]
      gamma: 0.1
      T_max: 300
      eta_min: 0
      warmup_factor: 0.001
      warmup_iters: 1000
      warmup_method: 'linear' # 'linear' | 'constant'

VAL:
  engine_name: 'ANOPREDInference'