SYSTEM:
  multigpus: false
  num_gpus: 2
  gpus: [0,1]
  cudnn:
    benchmark: false
    deterministic: true
    enable: true
  distributed:
    use: false
 
DATASET:
  name: 'Ped2'
  seed: 2020
  read_format: 'opencv'
  image_format: 'jpg'
  channel_num: 1
  channel_name: 'gray'
  train:
    data_path: './data/ped2/training/frames'
    clip_length: 16
    sampled_clip_length: 16
    frame_step: 1
    data_clip_step: 1
    gt_path: './data/ped2'
  val:
    data_path: './data/ped2/testing/frames'
    clip_length: 16
    sampled_clip_length: 16
    frame_step: 1
    clip_step: 1
    gt_path: './data/ped2'
  number_of_class: 1
  score_normalize: false
  score_type: 'normal'
  decidable_idx: 0
  decidable_idx_back: 16
  smooth:
    guassian: true
    guassian_sigma: [3,5,15,10,20,30]
  mini_dataset:
    samples: 100
  evaluate_function:
    name: 'ScoreAUCMetrics'
    result_type: 'score'
ARGUMENT:
  train:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5]
      std: [0.5]
    fliplr:
      use: true
      p: 0.5
    flipud:
      use: true
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      height: 128
      width: 128
      position: 'center'
  val:
    use: true
    resize:
      use: true
      height: 256
      width: 256
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5]
      std: [0.5]

MODEL:
  name: 'memae'
  type: 'e2e'
  parts: ['meta_AutoEncoderCov3DMem', 'MemAE']
  hooks:
    train: ['MemAEEvaluateHook', 'VisScoreHook']
    val: ['MemAEEvaluateHook']

TRAIN:
  engine_name: 'MEMAETrainer'
  batch_size: 4
  start_step: 0
  max_steps: 127600
  log_step: 100
  vis_step: 638
  mini_eval_step: 500
  eval_step: 638
  save_step: 638
  epochs: 1
  losses: ['loss_RecLoss_cuda', 1, 'L2Loss', [], 'loss_MemLoss_cuda', 0.0002, 'MemLoss', []]
  mode: 'general'
  general:
    optimizer:
      include: ['MemAE']
      name: 'adam'
      lrs: [1e-3]
      momentum: 0.9
      weight_decay: 0.1
      nesterov: false
    scheduler:
      use: true
      name: 'MultiStepLR'
      step_size: 1000
      steps: [63800, 127600]
      gamma: 0.1
      T_max: 6380
      eta_min: 0
      warmup_factor: 0.001
      warmup_iters: 1276
      warmup_method: 'linear'
  model_output: './output/models'
  checkpoint_output: './output/checkpoint'

VAL:
  engine_name: 'MEMAEInference'
  name: ''
  path: ''
  batch_size: 2
  result_output: './output/results'

