SYSTEM:
  gpus: [0,1]
  cudnn:
    benchmark: false
    deterministic: true
    enable: true
  
DATASET:
  name: 'Avenue'
  seed: 2020
  read_format: 'opencv'
  channel_num: 3
  channel_name: 'rgb'
  train:
    data_path: './data/Avenue/training/frames'
    clip_length: 2
    frame_step: 1
    clip_step: 1
    gt_path: './data/Avenue'
  val:
    data_path: './data/Avenue/testing/frames'
    clip_length: 2
    frame_step: 1
    clip_step: 1
    gt_path: './data/Avenue'
  number_of_class: 1
  score_normalize: true
  score_type: 'abnormal'
  decidable_idx: 1
  smooth:
    guassian: true
    guassian_sigma: [3,5,15,10,20]
  mini_dataset:
    samples: 100
  evaluate_function:
    name: 'ScoreAUCMetrics'
    result_type: 'score'

ARGUMENT:
  train:
    use: true
    resize:
      use: true
      height: 128
      width: 192
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5, 0.5, 0.5]
      std: [0.5,0.5,0.5]
    fliplr:
      use: false
      p: 0.5
    flipud:
      use: false
      p: 0.5
    rote:
      use: false
      degrees: [10,10]
    JpegCompression:
      use: false
      high: 100
      low: 80
    GaussianBlur:
      use: false
      high: 0.3
      low: 0.03
    CropToFixedSize:
      use: false
      height: 256
      width: 256
      position: 'center'
  val:
    use: true
    resize:
      use: true
      height: 128
      width: 192
    grayscale:
      use: false
    normal:
      use: true
      mean: [0.5,0.5,0.5]
      std: [0.5,0.5,0.5]

MODEL:
  name: 'amc'
  type: 'ame2e'
  parts: ['meta_G', 'AMCGenerator', 'meta_D', 'AMCDiscriminiator', 'auxiliary_F', 'FlowNet2']
  hooks:
    train: ['AMCEvaluateHook', 'VisScoreHook']
    val: ['AMCEvaluateHook']
  discriminator_channels: [128,256,512,512]
  auxiliary:
    optical_flow:
      name: 'flownet2'
      model_path: './pretrained_model/FlowNet2_checkpoint.pth.tar'

TRAIN:
  engine_name: 'AMCTrainer'
  batch_size: 16
  start_step: 0
  max_steps: 38320
  log_step: 5
  vis_step: 958
  eval_step: 958
  save_step: 958
  losses: ['loss_GANLoss_cuda', 0.25, 'GANLoss', [['gan_mode', vanilla], ['target_real_label', 1.0], ['target_fake_label', 0.0]], 'loss_GradientLoss_cuda', 1.0, 'GradientLoss', [], 
           'loss_IntentsityLoss_cuda', 1.0, 'IntensityLoss', [], 'loss_OpticalflowSqrtLoss_cuda', 2.0, 'L2Loss', []]
  mode: 'adversarial'
  adversarial:
    optimizer:
      include: ['G', 'D']
      name: 'adam'
      lrs: [2e-4, 2e-5]
      betas: [0.5, 0.9]
      weight_decay: 0.0001
    scheduler:
      use: true
      name: 'WarmupMultiStepLR'
      step_size: 1916
      steps: [9580,28740]
      gamma: 0.1
      T_max: 300
      eta_min: 0
      warmup_factor: 0.01
      warmup_iters: 958
      warmup_method: 'linear'

VAL:
  engine_name: 'AMCInference'

